'use client';
import {useState} from 'react';
import {ArrowRight, BookOpen, ChevronLeft, Clock3, GraduationCap, Info, MapPin, Phone, Search, UsersRound, X} from './icons';
import type {School,Stream} from '@/data/schools';
type Item=School&{distanceKm:number|null};
const streams:Array<'הכול'|Stream>=['ממלכתי','הכול','ממלכתי דתי','ממלכתי חרדי','חרדי / מוכש״ר','ממלכתי ערבי'];
const explanations:Record<Stream,string>={
'ממלכתי':'חינוך ציבורי בפיקוח המדינה, עם תכנית לימודים כללית. בתי הספר שבמסנן הזה מלמדים בעברית.',
'ממלכתי דתי':'חינוך ציבורי בפיקוח המדינה המשלב תכנית לימודים כללית עם לימודי קודש ואורח חיים דתי.',
'ממלכתי חרדי':'חינוך חרדי רשמי בפיקוח מלא של משרד החינוך, עם לימודי ליבה בהיקף מלא.',
'חרדי / מוכש״ר':'מוסדות חרדיים בזרמים שונים. מוכר שאינו רשמי (מוכש״ר) הוא מעמד של מוסד מוכר שאינו בבעלות המדינה או הרשות; התנאים משתנים בין מוסדות.',
'ממלכתי ערבי':'חינוך ממלכתי ציבורי במגזר הערבי, ששפת ההוראה בו היא ערבית. בית הספר מלמד גם עברית.',
};
const explanationSource='https://www.gov.il/BlobFolder/news/news-education100724/he/Education100724.pdf';
const performance={below:'מתחת לבתי ספר דומים',similar:'סביב בתי ספר דומים',above:'מעל בתי ספר דומים'};
const travel=(s:Item)=>s.travelEstimate?`הליכה כ־${s.travelEstimate.walk[0]}–${s.travelEstimate.walk[1]} דק׳ · נסיעה כ־${s.travelEstimate.drive[0]}–${s.travelEstimate.drive[1]} דק׳`:'אין אומדן זמן זמין';
export default function Explorer({schools}:{schools:Item[]}){
const [showExplanation,setShowExplanation]=useState(false);
const [tab,setTab]=useState<'schools'|'compare'>('schools'),[filter,setFilter]=useState<'הכול'|Stream>('ממלכתי'),[query,setQuery]=useState(''),[chosen,setChosen]=useState<string[]>([]),[active,setActive]=useState<Item|null>(null);
const visible=schools.filter(s=>(filter==='הכול'||s.stream===filter)&&s.name.includes(query.trim()));
const selected=chosen.map(id=>schools.find(s=>s.id===id)).filter((s):s is Item=>!!s);
const toggle=(id:string)=>setChosen(c=>c.includes(id)?c.filter(x=>x!==id):c.length<3?[...c,id]:c);
return <div className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><BookOpen size={19}/></span><span>למצוא מקום לגדול<small>בתי הספר של לוד, במבט קרוב</small></span></div><span className="top-note">מדריך משפחתי</span></header><main>
{active?<div className="detail"><button className="back" onClick={()=>setActive(null)}><ArrowRight size={18}/> חזרה לבתי הספר</button><div className="detail-head"><span className="eyebrow">להכיר מקרוב / {active.stream}</span><h1>{active.name}</h1><p><MapPin size={16}/>{active.address||'כתובת לא זמינה'}</p><div className="detail-meta"><span>{active.grades||'בית ספר יסודי'}</span>{active.phone&&<a href={`tel:${active.phone}`}><Phone size={15}/><bdi>{active.phone}</bdi></a>}</div></div><div className="detail-grid">
<section className="panel feature"><span className="section-icon"><Clock3 size={22}/></span><h2>מהבית שלנו</h2><strong className="travel-time">{active.travelEstimate?`הליכה כ־${active.travelEstimate.walk[0]}–${active.travelEstimate.walk[1]} דק׳`:'אין אומדן זמן זמין'}</strong>{active.travelEstimate&&<strong className="travel-time">נסיעה כ־{active.travelEstimate.drive[0]}–{active.travelEstimate.drive[1]} דק׳</strong>}<p>{active.travelEstimate?.basis||'לא נמצא בסיס מספיק לאומדן'}</p></section>
<section className="panel"><h2>גודל בית הספר</h2><div className="data-row"><span>תלמידים</span><b>{active.studentCount?.value?.toLocaleString('he-IL')??'אין נתון זמין'}</b></div><div className="data-row"><span>ממוצע בכיתה</span><b>{active.averageClassSize?.value??'אין נתון זמין'}</b></div><div className="data-row"><span>שכבות</span><b>{active.grades??'אין נתון זמין'}</b></div></section>
<section className="panel"><h2>הישגים לימודיים</h2><div className="data-row"><span>שפה</span><b>{active.languagePerformance?performance[active.languagePerformance.value]:'אין נתון זמין'}</b></div><p className="muted">השוואה לבתי ספר דומים לפי ראמ״ה, כאשר יש נתון מאומת.</p></section>
<section className="panel"><h2>אקלים בית ספרי</h2>{([['תחושת שייכות',active.climateMetrics?.belonging],['מוגנות',active.climateMetrics?.safety],['יחסים עם הצוות',active.climateMetrics?.relationships],['מנהיגות',active.climateMetrics?.leadership]] as const).map(([label,metric])=><div className="data-row" key={label}><span>{label}</span><b>{metric?`${metric.value}%`:'אין נתון זמין'}</b></div>)}</section>
<section className="panel"><h2>אופי ומאפיינים</h2><p>{active.specialCharacteristics?.join(' · ')||'אין כרגע נתון ציבורי זמין'}</p><p className="muted">זרם הלימוד: {active.stream}</p></section>
<section className="panel"><h2>מקורות</h2><p className="muted">פרטי קשר וכתובות לפי רשימת עיריית לוד, נבדקו בספטמבר 2026. שנת נתוני הישגים תופיע כאשר יאומתו.</p><ul className="sources">{active.sources.map(src=><li key={src.url}><a href={src.url} target="_blank" rel="noreferrer">{src.label} ↗</a></li>)}</ul></section></div><button className="primary wide" disabled={!chosen.includes(active.id)&&chosen.length>=3} onClick={()=>toggle(active.id)}>{chosen.includes(active.id)?'הסר מההשוואה':chosen.length>=3?'אפשר להשוות עד 3 בתי ספר':'הוסף להשוואה'}</button></div>:<><div className="intro"><div className="intro-art" aria-hidden="true"><span>ל</span><i/><i/><i/></div><span className="eyebrow">מדריך בתי הספר / לוד</span><h1>{tab==='schools'?'מחפשים בית ספר':'השוואת בתי ספר'}</h1><p>{tab==='schools'?'כל המידע על בתי הספר היסודיים בלוד במקום אחד':'הפרטים החשובים, אחד ליד השני'}</p></div>
{tab==='schools'&&<><div className="search"><Search size={21} aria-hidden="true"/><input aria-label="חיפוש בית ספר" value={query} onChange={e=>setQuery(e.target.value)} placeholder="חיפוש לפי שם בית הספר" /></div><div className="chips" aria-label="סינון לפי זרם">{streams.map(stream=><button key={stream} className={filter===stream?'chip active':'chip'} onClick={()=>{setFilter(stream);setShowExplanation(stream!=='הכול')}}>{stream}</button>)}</div>{showExplanation&&filter!=='הכול'&&<aside className="stream-explanation"><div className="explanation-icon"><Info size={20}/></div><div><strong>מה זה {filter}?</strong><p>{explanations[filter]}</p><a href={explanationSource} target="_blank" rel="noreferrer">על מסלולי החינוך ↗</a></div><button aria-label="סגירת ההסבר" onClick={()=>setShowExplanation(false)}><X size={18}/></button></aside>}<div className="section-title"><h2>בתי ספר</h2><span>{visible.length} בתי ספר</span></div><div className="cards">{visible.map(s=><article className="school-card" key={s.id}><button className="card-body" onClick={()=>setActive(s)}><span className="school-icon"><GraduationCap size={24}/></span><span className="card-text"><span className="stream">{s.stream}</span><strong>{s.name}</strong><span className="address">{s.address||'כתובת לא זמינה'}</span></span><span className="chevron"><ChevronLeft size={23}/></span></button><div className="card-facts"><span><Clock3 size={15}/> {travel(s)}</span>{s.studentCount&&<span><UsersRound size={15}/> {s.studentCount.value} תלמידים</span>}</div><div className="card-foot"><span>{s.languagePerformance?`שפה: ${performance[s.languagePerformance.value]}`:'מידע לימודי נוסף יתווסף כשיאומת'}</span><button className={chosen.includes(s.id)?'compare-btn picked':'compare-btn'} onClick={()=>toggle(s.id)} disabled={!chosen.includes(s.id)&&chosen.length>=3}>{chosen.includes(s.id)?'✓ נבחר':'＋ השווה'}</button></div></article>)}</div>{visible.length===0&&<div className="empty">לא נמצאו בתי ספר בסינון הזה.</div>}</>}
{tab==='compare'&&<div className="comparison">{selected.length<2?<div className="empty"><b>בחרו לפחות שני בתי ספר להשוואה</b><p>אפשר לבחור עד שלושה דרך כפתור ״השווה״ בכרטיסים.</p><button className="primary" onClick={()=>setTab('schools')}>לבתי הספר</button></div>:<><div className="selected-list">{selected.map(s=><button key={s.id} onClick={()=>toggle(s.id)}>{s.name} ×</button>)}</div>{([['זמן הליכה ונסיעה משוער',(s:Item)=>travel(s)],['מספר תלמידים',(s:Item)=>s.studentCount?.value?.toLocaleString('he-IL')||'אין נתון זמין'],['ממוצע תלמידים בכיתה',(s:Item)=>String(s.averageClassSize?.value??'אין נתון זמין')],['שפה',(s:Item)=>s.languagePerformance?performance[s.languagePerformance.value]:'אין נתון זמין'],['זרם',(s:Item)=>s.stream]] as [string,(s:Item)=>string][]).map(([title,read])=><section className="panel compare-panel" key={title}><h2>{title}</h2>{selected.map(s=><div className="compare-row" key={s.id}><span>{s.name}</span><b>{read(s)}</b></div>)}</section>)}</>}</div>}</>}</main><nav className="bottom-nav" aria-label="ניווט ראשי">{([['schools','בתי ספר','⌂'],['compare',`השוואה${chosen.length?` (${chosen.length})`:''}`,'▤']] as const).map(([id,label,icon])=><button key={id} className={!active&&tab===id?'current':''} onClick={()=>{setActive(null);setTab(id)}}><span aria-hidden>{icon}</span>{label}</button>)}</nav></div>}
