'use client';
import {useCallback,useState} from 'react';
import dynamic from 'next/dynamic';
import {AlertMark, ArrowRight, BookOpen, ChevronLeft, Info, Kippah, MapPin, Pencil, Phone, SchoolBag, Search, UsersRound, X} from './icons';
import type {School,Stream} from '@/data/schools';
const SchoolMap=dynamic(()=>import('./school-map'),{ssr:false,loading:()=> <div className="map-loading">המפה נטענת…</div>});
type Home={lat:number;lng:number;label:string;source:{label:string;url:string}};
const streams:Array<'הכול'|Stream>=['הכול','ממלכתי','ממלכתי דתי','ממלכתי חרדי','חרדי / מוכש״ר','ממלכתי ערבי'];
const explanations:Record<Stream,string>={
'ממלכתי':'מסלול ציבורי בפיקוח משרד החינוך, עם הוראה בעברית של מקצועות הליבה, חברה ותרבות יהודית־ישראלית. ברוב בתי הספר לומדים בנים ובנות יחד, ואין תפילה דתית קבועה כחלק מחייב מיום הלימודים. ייתכנו אירועי מסורת או יוזמות מקומיות, ולכן כדאי לברר את סדר היום של כל בית ספר.',
'ממלכתי דתי':'מסלול ציבורי המשלב מקצועות ליבה עם לימודי תורה, הלכה וערכים דתיים. תפילה היא בדרך כלל חלק מסדר היום. בחלק מהמוסדות לומדים בנים ובנות יחד, באחרים יש כיתות נפרדות או בתי ספר נפרדים; גם היקף התפילה והמנהגים משתנים לפי גיל ולפי בית הספר.',
'ממלכתי חרדי':'מסלול חרדי רשמי בפיקוח מלא של משרד החינוך, עם לימודי ליבה בהיקף מלא לצד לימודי קודש ואורח חיים חרדי. בדרך כלל יש תפילות והפרדה בין בנים לבנות, אך צורת הארגון המדויקת נקבעת במוסד. חשוב לבדוק ישירות אילו שכבות, מסורת קהילתית ונהלים פועלים בו.',
'חרדי / מוכש״ר':'קבוצה של מוסדות חרדיים במעמדות שונים; מוכר שאינו רשמי הוא מעמד של בית ספר מוכר שאינו בבעלות המדינה או הרשות. בדרך כלל לימודי קודש ותפילות מרכזיים בסדר היום, והלימודים מתקיימים בהפרדה בין בנים לבנות. היקף לימודי הליבה, התפילה וכללי הקבלה שונים ממוסד למוסד, ולכן שם הזרם לבדו אינו מספיק כדי לתאר בית ספר מסוים.',
'ממלכתי ערבי':'מסלול ציבורי בפיקוח המדינה שבו שפת ההוראה המרכזית היא ערבית, ונלמדים גם עברית ומקצועות הליבה. בדרך כלל בנים ובנות לומדים יחד. לימודי דת ופעילות דתית תלויים בתכנית ובקהילה של בית הספר; אין להסיק מהסיווג לבדו שמתקיימת תפילה יומית או הפרדה בין המינים.',
};
const explanationSource='https://www.gov.il/BlobFolder/news/news-education100724/he/Education100724.pdf';
const mixGuide='הזרם מתאר פיקוח ושפת הוראה, ולא קובע לבדו מי לומד בבית הספר. מפגשים בין בתי ספר יהודיים וערביים אינם מעידים שהתלמידים לומדים באותן כיתות.';
const StreamIcon=({stream,size=23}:{stream:Stream;size?:number})=><span className="stream-icons"><span><SchoolBag size={size}/></span>{stream==='ממלכתי'&&<Pencil size={Math.round(size*.7)}/>} {stream==='ממלכתי דתי'&&<Kippah size={Math.round(size*.75)}/>} {stream==='ממלכתי חרדי'&&<Kippah size={Math.round(size*.75)}/>} {stream==='חרדי / מוכש״ר'&&<BookOpen size={Math.round(size*.7)}/>} {stream==='ממלכתי ערבי'&&<BookOpen size={Math.round(size*.7)}/>}</span>;

export default function Explorer({schools,home}:{schools:School[];home:Home}){
  const [showExplanation,setShowExplanation]=useState(false);
  const [tab,setTab]=useState<'schools'|'map'>('schools');
  const [filter,setFilter]=useState<'הכול'|Stream|null>(null);
  const [query,setQuery]=useState('');
  const [active,setActive]=useState<School|null>(null);
  const openSchool=useCallback((id:string)=>{const found=schools.find(s=>s.id===id);if(found){setActive(found);window.scrollTo({top:0,behavior:'instant'});}},[schools]);
  const visible=schools.filter(s=>(filter===null||filter==='הכול'||s.stream===filter)&&s.name.includes(query.trim()));
  return <div className="shell"><main>
    {active?<div className="detail">
      <button className="back" onClick={()=>setActive(null)}><ArrowRight size={18}/> {tab==='map'?'חזרה למפה':'חזרה לבתי הספר'}</button>
      <div className="detail-head"><span className="eyebrow">להכיר מקרוב / {active.stream}</span><h1>{active.name}</h1><p><MapPin size={16}/>{active.address||'כתובת לא זמינה'}</p><div className="detail-meta"><span>שכבות {active.grades||'לא ידועות'}</span>{active.gender&&<span>{active.gender}</span>}{active.phone&&<a href={`tel:${active.phone}`}><Phone size={15}/><bdi>{active.phone}</bdi></a>}</div></div>
      <div className="detail-grid">
        <section className="panel"><h2>גודל בית הספר</h2><div className="data-row"><span>תלמידים ({active.studentCount?.year||'שנה לא ידועה'})</span><b>{active.studentCount?.value?.toLocaleString('he-IL')??'אין נתון זמין'}</b></div><div className="data-row"><span>כיתות ({active.classCount?.year||'שנה לא ידועה'})</span><b>{active.classCount?.value??'אין נתון זמין'}</b></div><div className="data-row"><span>ממוצע תלמידים בכיתה ({active.averageClassSize?.year||'שנה לא ידועה'})</span><b>{active.averageClassSize?.value??'אין נתון זמין'}</b></div><div className="data-row"><span>שכבות</span><b>{active.grades??'אין נתון זמין'}</b></div></section>
        <section className="panel"><h2>הישגים לימודיים</h2>{active.learningMetrics?.length?active.learningMetrics.map((m,i)=><div className="metric-line" key={i}><span>{m.label} · {m.grades} · {m.year}</span><b>{m.value}</b></div>):<p>אין נתון זמין</p>}<div className="measure-help"><strong><Info size={17}/> איך לקרוא את מדד שפת האם?</strong><p>ראמ״ה בודקת מיומנויות בשפת האם של התלמידים בשכבות שמצוינות מעל. ״כמו ממוצע הדומים״ פירושו שהתוצאה קרובה לממוצע של בתי ספר בעלי מאפיינים דומים; ״נמוך במעט״ או ״גבוה במעט״ מתארים פער יחסי מאותה קבוצת השוואה. זה אינו ציון ממוצע של תלמידי בית הספר, אינו דירוג שלו, ואינו מאפשר להשוות בלי להתחשב בשנה ובשכבה. באתר המקור לא פורסם כאן ציון מספרי להשוואה.</p></div></section>
        <section className="panel"><h2>אקלים בית ספרי</h2>{active.climateComparisons?.length?active.climateComparisons.map((m,i)=><div className="metric-line" key={i}><span>{m.label} · {m.grades} · {m.year}</span><b>{m.value}</b></div>):<p>אין נתון זמין</p>}<p className="muted">תוצאות סקרים ביחס לבתי ספר דומים; אינן ציון כללי לבית הספר.</p></section>
        <section className="panel"><h2>אופי ותכנית לימודים</h2><div className="stream-brief"><StreamIcon stream={active.stream}/><b>{active.stream}</b></div><p>{explanations[active.stream]}</p><p className="muted">שכבות לימוד: {active.grades||'אין נתון ציבורי זמין'}. תכנית ייחודית למוסד: {active.specialCharacteristics?.join(' · ')||'אין כרגע נתון ציבורי זמין'}.</p></section>
        <section className="panel"><h2>האם לומדים יחד תלמידים יהודים וערבים?</h2><p>{active.populationMix?.text||'אין כרגע נתון ציבורי זמין'}</p>{active.populationMix?.source&&<p className="source-inline">לפי <a href={active.populationMix.source.url} target="_blank" rel="noreferrer">{active.populationMix.source.label} ↗</a> {active.populationMix.year&&`(${active.populationMix.year})`}</p>}<p className="muted">{mixGuide}</p></section>
        <section className="panel events-panel"><h2><AlertMark size={20}/> אירועים מתועדים</h2>{active.events?.length?active.events.map((event,i)=><article className="event-item" key={i}><span className={event.kind==='רישום ושוויון'?'event-type historical':'event-type'}>{event.kind} · {event.year}</span><h3>{event.title}</h3><p>{event.detail}</p><a href={event.source.url} target="_blank" rel="noreferrer">מקור: {event.source.label} ↗</a></article>):<p>לא נמצא כרגע אירוע מתועד במקורות שנבדקו. זה אינו מעיד שלא התרחשו אירועים.</p>}<p className="muted">סקירה של פרסומים ציבוריים, לא רשימת אירועים מלאה או עדכנית בזמן אמת. אירוע ישן אינו תיאור של המצב כיום.</p></section>
        <section className="panel"><h2>מקורות</h2>{active.notes&&<p className="source-note">{active.notes}</p>}<p className="muted">פרטי הקשר מתוך עיריית לוד. תלמידים וממוצע בכיתה: נתוני משרד החינוך 2024 כפי שמוצגים ב־GoInfo. מדדי ראמ״ה מוצגים עם שנת המדידה.</p><ul className="sources">{active.sources.map(src=><li key={src.url}><a href={src.url} target="_blank" rel="noreferrer">{src.label} ↗</a></li>)}</ul></section>
      </div>
    </div>:<>
      <div className="intro"><span className="eyebrow">מידע ציבורי · לוד</span><h1>{tab==='schools'?'סקירת בתי ספר יסודיים בלוד':'בתי הספר על המפה'}</h1><p>{tab==='schools'?'בתי הספר, הנתונים והפרטים החשובים — במקום אחד':'לוד במבט אחד: הבית ובתי הספר היסודיים'}</p></div>
      {tab==='schools'?<>
        <div className="search"><Search size={21} aria-hidden="true"/><input aria-label="חיפוש בית ספר" value={query} onChange={e=>setQuery(e.target.value)} placeholder="חיפוש לפי שם בית הספר" /></div>
        <p className="filter-prompt">אנא בחרו את סוג החינוך</p><div className="chips" aria-label="סינון לפי זרם">{streams.map(stream=><button key={stream} className={filter===stream?'chip active':'chip'} onClick={()=>{setFilter(stream);setShowExplanation(stream!=='הכול')}}>{stream}</button>)}</div>
        {showExplanation&&filter!==null&&filter!=='הכול'&&<aside className="stream-explanation"><div className="explanation-icon"><Info size={20}/></div><div><strong>מה זה {filter}?</strong><p>{explanations[filter]}</p><p>{mixGuide}</p><a href={explanationSource} target="_blank" rel="noreferrer">על מסלולי החינוך ↗</a></div><button aria-label="סגירת ההסבר" onClick={()=>setShowExplanation(false)}><X size={18}/></button></aside>}
        <div className="section-title"><h2>בתי ספר</h2><span>{visible.length} בתי ספר</span></div>
        <div className="cards">{visible.map(s=><article className="school-card" key={s.id}><button className="card-body" onClick={()=>openSchool(s.id)}><span className="school-icon"><StreamIcon stream={s.stream} size={25}/></span><span className="card-text"><span className="stream">{s.stream}</span><strong>{s.name}</strong><span className="address">{s.address||'כתובת לא זמינה'}</span><span className="grade-badge">כיתות {s.grades||'לא ידועות'}</span></span><span className="chevron"><ChevronLeft size={23}/></span></button><div className="card-facts">{s.studentCount&&<span><UsersRound size={16}/> {s.studentCount.value.toLocaleString('he-IL')} תלמידים · {s.studentCount.year}</span>}<span><UsersRound size={16}/> ממוצע בכיתה: {s.averageClassSize?`${s.averageClassSize.value} תלמידים · ${s.averageClassSize.year}`:'אין נתון זמין'}</span></div><div className="card-story">{s.events?.length?<button onClick={()=>openSchool(s.id)}><AlertMark size={16}/> {s.events.some(e=>e.kind==='רישום ושוויון')?'אירוע היסטורי והישגים מתועדים':s.events.length===1?'אירוע מתועד אחד':`${s.events.length} אירועים והישגים מתועדים`} <ChevronLeft size={14}/></button>:<span>לא נמצאו אירועים מתועדים בסקירה</span>}</div><div className="card-foot"><span>{s.learningMetrics?.[0]?`שפת אם: ${s.learningMetrics[0].value} (${s.learningMetrics[0].grades})`:'נתוני ראמ״ה לא זמינים'}<small>ביחס לבתי ספר דומים · הסבר בפנים</small></span><button className="card-details" onClick={()=>openSchool(s.id)}>לפרטים <ChevronLeft size={16}/></button></div></article>)}</div>{visible.length===0&&<div className="empty">לא נמצאו בתי ספר בסינון הזה.</div>}
      </>:<SchoolMap schools={schools} home={home} onOpen={openSchool}/>}
    </>}
  </main><nav className="bottom-nav" aria-label="ניווט ראשי"><button className={!active&&tab==='schools'?'current':''} onClick={()=>{setActive(null);setTab('schools')}}><span aria-hidden>⌂</span>בתי ספר</button><button className={!active&&tab==='map'?'current':''} onClick={()=>{setActive(null);setTab('map')}}><MapPin size={20}/>מפה</button></nav></div>;
}
